[[stack]]
name = "meine-app-2"
description = "Mein Homelab Stack 2"
branch = "main"
auto_update = true

[stack.config]
server_id = "unraid"
git_provider = "github.com"
git_account = "mirisbowring"
repo = "mirisbowring/test"
run_directory = "stack2/"

[env]
ENV1 = "value1"
ENV2 = "value2"
