[[stack]]
name = "my-stack"
description = "my super cool description"
tags = ["media", "prod"]
[stack.config]
server = "unraid"
auto_update = true
auto_update_all_services = true
git_account = "mirisbowring"
repo = "mirisbowring/test"
run_directory = "stack1/"
