name = "homebox"
description = "Self-hosted Homebox inventory"
path = "stack1/docker-compose.yml"
branch = "main"
auto_update = true

# Optional: statische Umgebungsvariablen (wenn du keine .env verwendest)
#[env]
#HOMEBOX_SECRET = "supersecure"
